# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-disabled-in-the-docker-executor
# https://docs.gitlab.com/ee/ci/services/#accessing-the-services

stages:
  - replace
  - build

#########################
#        Replace        #
#########################

replace:
  stage: replace
  tags:
    - linux
    - docker
  image: docker.io/library/almalinux:9
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - dnf install -y wget unzip
    - wget -O ./mastodon.zip https://github.com/mastodon/mastodon/archive/refs/tags/v4.3.6.zip
    - unzip -d ./mastodon ./mastodon.zip
    - rm -f ./mastodon.zip
    - mv ./mastodon/mastodon-*/* ./mastodon/mastodon-*/.[^.]* ./mastodon/
    - rmdir ./mastodon/mastodon-*/
    - cp -r ./src/* ./mastodon/
    - tar -zcvf ./mastodon.tar.gz ./mastodon/
  artifacts:
    paths:
      - ./mastodon.tar.gz

#########################
#         Build         #
#########################

docker-build:
  stage: build
  tags:
    - linux
    - docker
    - amd64
    - hpc
  image: docker.io/library/docker:cli
  services:
    - name: docker.io/library/docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    TARGETPLATFORM: linux/amd64
    BUILDPLATFORM: linux/amd64
    GITHUB_REPOSITORY: yanranxiaoxi/mastodon-sora
    MASTODON_VERSION_METADATA: sora
  rules:
  - if: $CI_COMMIT_TAG
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin docker.io
    - echo "$CI_JOB_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
  script:
    # 解包并构建
    - tar -zxvf ./mastodon.tar.gz
    - docker build --pull -t "mastodon-sora:$CI_COMMIT_TAG" ./mastodon/
    - docker tag mastodon-sora:$CI_COMMIT_TAG mastodon-sora:stable
    # 为 Docker Hub 打远程仓库标签
    - docker tag mastodon-sora:$CI_COMMIT_TAG docker.io/$DOCKERHUB_USER/mastodon-sora:$CI_COMMIT_TAG
    - docker tag mastodon-sora:stable docker.io/$DOCKERHUB_USER/mastodon-sora:stable
    # 为私有仓库打远程仓库标签
    - docker tag mastodon-sora:$CI_COMMIT_TAG $CI_REGISTRY/xiaoxi/mastodon-sora:$CI_COMMIT_TAG
    - docker tag mastodon-sora:stable $CI_REGISTRY/xiaoxi/mastodon-sora:stable
    # 推送 Docker Hub
    - docker push docker.io/$DOCKERHUB_USER/mastodon-sora:$CI_COMMIT_TAG
    - docker push docker.io/$DOCKERHUB_USER/mastodon-sora:stable
    # 推送私有仓库
    - docker push $CI_REGISTRY/xiaoxi/mastodon-sora:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY/xiaoxi/mastodon-sora:stable
