# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-disabled-in-the-docker-executor
# https://docs.gitlab.com/ee/ci/services/#accessing-the-services

stages:
  - replace
  - build

#########################
#        Replace        #
#########################

replace:
  stage: replace
  tags:
    - linux
    - docker
  image: docker.io/library/almalinux:9
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - dnf install -y wget unzip
    - wget -O ./mastodon.zip https://github.com/mastodon/mastodon/archive/refs/tags/v4.3.2.zip
    - unzip -d ./mastodon ./mastodon.zip
    - rm -f ./mastodon.zip
    - mv ./mastodon/mastodon-*/* ./mastodon/mastodon-*/.[^.]* ./mastodon/
    - rmdir ./mastodon/mastodon-*/
    - cp -r ./src/* ./mastodon/
    - tar -zcvf ./mastodon.tar.gz ./mastodon/
  artifacts:
    paths:
      - ./mastodon.tar.gz

#########################
#         Build         #
#########################

docker-build:
  stage: build
  tags:
    - linux
    - docker
    - amd64
    - hpc
  image: docker.io/library/docker:cli
  services:
    - name: docker.io/library/docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_IMAGE_NAME: $CONTAINER_REGISTRY_IMAGE:$CI_COMMIT_TAG
    TARGETPLATFORM: linux/amd64
    BUILDPLATFORM: linux/amd64
    GITHUB_REPOSITORY: yanranxiaoxi/mastodon-sora
    MASTODON_VERSION_METADATA: sora
  rules:
  - if: $CI_COMMIT_TAG
  before_script:
    - docker login -u "$CONTAINER_REGISTRY_USER" -p "$CONTAINER_REGISTRY_PASSWORD" $CONTAINER_REGISTRY
  script:
    - tar -zxvf ./mastodon.tar.gz
    - docker build --pull -t "$CONTAINER_IMAGE_NAME" ./mastodon/
    - docker push "$CONTAINER_IMAGE_NAME"
    - docker tag "$CONTAINER_IMAGE_NAME" "$CONTAINER_REGISTRY_IMAGE:stable"
    - docker push "$CONTAINER_REGISTRY_IMAGE:stable"
